apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  {{ include "helm.fullname" . }}
spec:
  prefix: /
  service: {{ include "helm.fullname" . }}.demo
  weight: {{ .Values.image.weight }}