#Basics - Actions
name: demo-start-31
env:
  APPLICATION_NAME: "demo-31"
  PACKAGE_NAME: "demo-31-ver-${{ github.sha }}.zip"
  EB_PACKAGE_S3_BUCKET_NAME: "elasticbeanstalk-eu-north-1-356347788863"
  EB_APP_NAME: "demo-31"
  EB_ENVIRONMENT_NAME: "Demo31-env"
  AWS_REGION_NAME: "eu-north-1"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  test_server:
    runs-on: ubuntu-latest
    steps:
      
      - name: Git clone repo
        uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: pip install -r requirements.txt
       
      - name: Main test
        run: |
          python "web server/test.py"

        
  
  deploy_app:
    runs-on: ubuntu-latest
    needs: [test_server]
    steps:
  
      - name: Git clone
        uses: actions/checkout@v1
      
      - name: Create ZIP deployment packege
        run: zip -r ${{ env.PACKAGE_NAME }} ./ -x *.git
        
      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
          
      - name: Copy to S3 bucket
        run: aws s3 cp ${{ env.PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}
          

   
    
