#Basics - Actions
name: demo-start-31
env:
  APPLICATION_NAME: "demo-31"
  PACKAGE_NAME: "flask_demo-ver-${{ github.sha }}"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test_server:
    runs-on: ubuntu-latest
    steps:
      
      - name: Git clone repo
        uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: pip install -r requirements.txt
       
      - name: Main test
        run: |
          python "web server/test.py"

        
  
  deploy_test:
    runs-on: ubuntu-latest
    needs: [test_server]
    steps:
      - name: Start server
        run: |
          echo "Test start....."
          

   
    
